### ISSUE TITLE
I am stuck on image placeholder!

### ISSUE THREAD

**Issue by kmiddlesworth** [AshtmlB/test-repository#1]
@AshtmlB - I have too many options! Foxes or bacon?

**Comment by AshtmlB** [comment]
@kmiddlesworth Definitely go with bacon

**Comment by AshtmlB** [comment]
@AshtmlB http://77d5-2601-249-1880-24e0-b82b-3be4-19b8-1e77.ngrok.io

**Comment by kmiddlesworth** [comment]
Bacon wins. Closing issue.
